name: Update Matches
on:
  schedule:
    - cron: '0 12 * * *'  # يومياً الساعة 12 ظهراً
  workflow_dispatch:       # يسمح بالتشغيل اليدوي

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
     - name: Update Matches Data
  run: |
    #  GET https://api.football-data.org/v4/matches
    echo '[{"home_team":"الاتحاد","away_team":"الشباب","date":"2023-10-16","time":"21:00"}]' > matches.json
          
      - name: Commit Changes
        run: |
          git config --global user.name "GitHub Bot"
          git config --global user.email "bot@example.com"
          git add .
          git commit -m "Auto-update matches data"
          git push
